modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://gitlab.com/DragonForge/<NAME>/issues"
license = "All rights reserved"

[[mods]]
modId = "equivadds"
version = "${file.jarVersion}"
displayName = "Equivalent Additions"
updateJSONURL = "http://h.zeith.org/api/fmluc/303583"
displayURL = "http://dccg.herokuapp.com/api/fmlhp/303583"
logoFile = "equivadds.png" #optional
credits = "None" #optional
authors = "Zeitheron" #optional
description = '''
Multi-line description
of the mod!
'''

[[dependencies.equivadds]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"
[[dependencies.equivadds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.equivadds]]
modId = "hammerlib"
mandatory = true
versionRange = "[19.3.51,)"
ordering = "NONE"
side = "BOTH"
